server:  
    port: 8082
    session-timeout: 30
    tomcat.max-threads: 0
    tomcat.uri-encoding: UTF-8
    servlet:
      context-path: /receive
spring:
    cache:
        caffeine:
          spec: maximumSize=500,expireAfterWrite=10s
        type: caffeine
        cache-names:
          - test
          - info
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/shandong_manager?useUnicode:true&characterEncoding:utf-8
        username: root
        password: cyber
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        checkTemplateLocation: false
    redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          #最大连接数
          max-active: 1000
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 1
      #连接超时时间
      timeout: 10000
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      cache: false
