server:  
    port: 9000
    session-timeout: 30
    servlet:
      context-path: /receive
    tomcat:
      max-http-header-size: 8192
      max-threads: 0
      uri-encoding: UTF-8
spring:
    messages:
        basename: i18n/code,i18n/resouse
        encoding: UTF-8
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/receive_manager?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: cyber
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    freemarker:
        checkTemplateLocation: false
    redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password: cyber
      jedis:
        pool:
          #最大连接数
          max-active: 10000
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 1
      #连接超时时间
      timeout: 10000
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML5
      cache: false
    servlet:
      multipart:
        max-request-size: 120MB # 总上传最大限制
        max-file-size: 100MB
code:
   project-environment: inter
#   socket-port: 8081
#   socket-url: 192.168.20.182
   socket-port: 8084
#   socket-url: 192.168.1.206
   socket-url: 127.0.0.1
   thread-pool-size: 1000
   file-sever-port: 8082
#   file-save-parh: /home/upFile
   file-save-path: D:\\source\\
   #55兆字节(mb)=57671680字节(b)
