server:  
    port: 8083
    session-timeout: 30
    tomcat.max-threads: 0
    tomcat.uri-encoding: UTF-8
    servlet:
      context-path: /forward
spring:
    redis:
      #数据库索引
      database: 0
      host: 127.0.0.1
      port: 6379
      password: cyber
      jedis:
        pool:
          #最大连接数
          max-active: 1000
          #最大阻塞等待时间(负数表示没限制)
          max-wait: -1
          #最大空闲
          max-idle: 8
          #最小空闲
          min-idle: 1
      #连接超时时间
      timeout: 10000

code:
   #互联网
   project-environment: inter
#   socket-url: 192.168.20.182
   #移动网
#   project-environment: model
#   socket-url: 192.168.22.131
    #本机测试
   socket-url: 192.168.1.206
   socket-server-port: 8084
   socket-client-port: 8084
#   socket-port: 8083
   request-maxtime: 30000
   request-sleeptime: 500
   thread-pool-size: 1000
   cache_time: 30000
   file-sever-port: 8082
#   file-save-parh: /home/upFile
   file-save-parh: D:\\source\\
   message:
       0: 查询成功
       99101: 服务接口请求超时
       99102: 服务接口连接失败
       99103: 访问内网异常
       99104: 请求的参数中缺少查询条件
       99105: 请求的参数中appkey元素为空
       99106: 请求的参数中servicekey元素为空
       99107: 请求的参数中serviceurl元素为空
       99108: 请检查appKey或serviceKey是否正确